In [1]:
import pandas as pd
import numpy as np

In [2]:
rfid=pd.read_excel('test1.xlsx',sheet_name='RFID data_2019.05.30 - 31')

In [3]:
rfid.head()

,Date/time,logId,RFID_gate,RFID_id,Area
0,2019-05-30 01:11:51,15505,Főbejárat I.,100019790,Esemény területén kívül
1,2019-05-30 06:16:22,22814,Főbejárat I.,100013440,Esemény területén kívül
2,2019-05-30 06:16:29,22817,Főbejárat I.,100013440,Esemény területén kívül
3,2019-05-30 06:16:33,22824,Főbejárat I.,100013440,Benti közös
4,2019-05-30 06:34:49,23262,Főbejárat III.,100037900,Esemény területén kívül

In [4]:
#import seaborn as sns
#sns.distplot(rfid['Area'],kde=False)

In [5]:
a = rfid['Area'].value_counts()
a

Benti közös                66022
Esemény területén kívül    33624
Big Hall                   18483
Secret Garden              16777
Fun Factory                 8994
Name: Area, dtype: int64

In [6]:
rfid.isna().sum()

Date/time    0
logId        0
RFID_gate    0
RFID_id      0
Area         0
dtype: int64

In [7]:
rfid['Date/time']=pd.to_datetime(rfid['Date/time'])

In [8]:
rfid.head()

,Date/time,logId,RFID_gate,RFID_id,Area
0,2019-05-30 01:11:51,15505,Főbejárat I.,100019790,Esemény területén kívül
1,2019-05-30 06:16:22,22814,Főbejárat I.,100013440,Esemény területén kívül
2,2019-05-30 06:16:29,22817,Főbejárat I.,100013440,Esemény területén kívül
3,2019-05-30 06:16:33,22824,Főbejárat I.,100013440,Benti közös
4,2019-05-30 06:34:49,23262,Főbejárat III.,100037900,Esemény területén kívül

In [9]:
agenda=pd.read_excel('test1.xlsx',sheet_name='Event agenda')

In [10]:
agenda.head()

,Session ID,Location ID,Track ID,Session Name,Format,Date Start,Date End,Speaker IDs,Speaker Names,Track,Location
0,8113,922,1029,STARY NIGHT How to reach the lifestyle of Haku...,MYTHBURN,30-05-19 10:00,30-05-19 10:30,"2185817, 2185872","Timon, Pumba",FUTURE OF HAPPINESS,Big Hall
1,8114,922,1030,DRAGONS OF THE UNIVERSE How to train your dragon?,ONE ON ONE,30-05-19 10:35,30-05-19 11:00,2182426,Hiccup,FUTURE OF BUSINESS,Big Hall
2,8115,922,1031,DREAMING OR NOT DREAMING Where are our dreams ...,TURNING POINT,30-05-19 11:00,30-05-19 11:40,2185889,Sleeping Beauty,FUTURE OF HUMANKIND,Big Hall
3,8116,922,1032,THE SECRET OF THE FLYING CARPET Do you trust t...,TURNING POINT,30-05-19 13:00,30-05-19 13:35,2187311,Aladdin,FUTURE OF STORYTELLING,Big Hall
4,8118,922,1033,JUNGLE VS CIVILIZATION What can be learnt from...,ONE ON ONE,30-05-19 13:35,30-05-19 14:05,"2185853, 2187303","Tarzan, Jane",FUTURE OF GEOPOLITICS,Big Hall

In [11]:
agenda['Date Start']=pd.to_datetime(agenda['Date Start'])
agenda['Date End']=pd.to_datetime(agenda['Date End'])

In [12]:
agenda.head()

,Session ID,Location ID,Track ID,Session Name,Format,Date Start,Date End,Speaker IDs,Speaker Names,Track,Location
0,8113,922,1029,STARY NIGHT How to reach the lifestyle of Haku...,MYTHBURN,2019-05-30 10:00:00,2019-05-30 10:30:00,"2185817, 2185872","Timon, Pumba",FUTURE OF HAPPINESS,Big Hall
1,8114,922,1030,DRAGONS OF THE UNIVERSE How to train your dragon?,ONE ON ONE,2019-05-30 10:35:00,2019-05-30 11:00:00,2182426,Hiccup,FUTURE OF BUSINESS,Big Hall
2,8115,922,1031,DREAMING OR NOT DREAMING Where are our dreams ...,TURNING POINT,2019-05-30 11:00:00,2019-05-30 11:40:00,2185889,Sleeping Beauty,FUTURE OF HUMANKIND,Big Hall
3,8116,922,1032,THE SECRET OF THE FLYING CARPET Do you trust t...,TURNING POINT,2019-05-30 13:00:00,2019-05-30 13:35:00,2187311,Aladdin,FUTURE OF STORYTELLING,Big Hall
4,8118,922,1033,JUNGLE VS CIVILIZATION What can be learnt from...,ONE ON ONE,2019-05-30 13:35:00,2019-05-30 14:05:00,"2185853, 2187303","Tarzan, Jane",FUTURE OF GEOPOLITICS,Big Hall

In [24]:
event_list = pd.DataFrame(columns=agenda['Session ID'].to_numpy())

event_list

Empty DataFrame
Columns: [8113, 8114, 8115, 8116, 8118, 8119, 8120, 8121, 8122, 8139, 8140, 8141, 8158, 8159, 8143, 8144, 8145, 8146, 8180, 8123, 8124, 8126, 8128, 8161, 8129, 8130, 8131, 8132, 8133, 8135, 8136, 8148, 8149, 8150, 8151, 8178, 8160, 8152, 8153, 8154, 8155, 8872]
Index: []

[0 rows x 42 columns]

In [58]:
for index, row in rfid.iterrows():
    
    for i, row1 in agenda.iterrows():
        
        if row['Date/time']>=row1['Date Start'] and row['Date/time']<=row1['Date End'] and
        (row['Area']=='Big Hall' or row['Area']=='Secret Garden'):
            
            event_list=event_list.append({row1['Session ID']:row['RFID_id']}, ignore_index=True)

In [59]:
!telegram-send "Готово!"

event_list

,8113,8114,8115,8116,8118,8119,8120,8121,8122,8139,...,8149,8150,8151,8178,8160,8152,8153,8154,8155,8872
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
event_list.nunique().sort_values(ascending=False)

8131    1108
8133    1085
8119    1077
8124    1053
8154    1049
8141    1009
8126     951
8145     841
8178     815
8115     764
8152     751
8161     750
8144     701
8872     685
8146     684
8132     677
8153     660
8136     651
8135     642
8128     621
8114     618
8149     611
8120     581
8139     581
8122     578
8113     565
8123     552
8180     530
8155     527
8143     512
8159     488
8158     466
8140     465
8121     435
8151     423
8160     362
8150     256
8118     253
8130     253
8148     198
8116       0
8129       0
dtype: int64

In [62]:
agenda[agenda['Session ID']==8131]

,Session ID,Location ID,Track ID,Session Name,Format,Date Start,Date End,Speaker IDs,Speaker Names,Track,Location
26,8131,923,1030,WAR OF THE MUSIC How to preserve our music her...,CHOSEN ONE,2019-05-30 14:15:00,2019-05-30 14:50:00,2187309,Miguel,FUTURE OF HUMANKIND,Secret Garden

In [67]:
rfid['Date/time'].sort_values(ascending=True)

0        2019-05-30 01:11:51
1        2019-05-30 06:16:22
2        2019-05-30 06:16:29
3        2019-05-30 06:16:33
4        2019-05-30 06:34:49
5        2019-05-30 06:34:54
6        2019-05-30 06:34:58
7        2019-05-30 06:35:00
8        2019-05-30 06:35:02
9        2019-05-30 06:35:05
10       2019-05-30 06:35:08
11       2019-05-30 06:35:09
12       2019-05-30 06:35:09
13       2019-05-30 06:35:17
15       2019-05-30 06:35:24
14       2019-05-30 06:35:24
16       2019-05-30 06:35:25
17       2019-05-30 06:35:25
18       2019-05-30 06:35:26
19       2019-05-30 06:35:27
20       2019-05-30 06:35:30
21       2019-05-30 06:35:35
22       2019-05-30 06:35:36
23       2019-05-30 06:35:40
24       2019-05-30 06:35:41
25       2019-05-30 06:35:42
26       2019-05-30 06:35:43
27       2019-05-30 06:35:48
28       2019-05-30 06:35:52
29       2019-05-30 06:36:01
                 ...
143870   2019-05-31 19:40:52
143871   2019-05-31 19:40:57
143872   2019-05-31 19:41:18
143873   2019-05-31 19:41:29
143874   2019-05-31 19:41:30
143875   2019-05-31 19:41:32
143876   2019-05-31 19:41:33
143877   2019-05-31 19:41:34
143878   2019-05-31 19:41:36
143879   2019-05-31 19:41:45
143880   2019-05-31 19:42:03
143881   2019-05-31 19:42:37
143882   2019-05-31 19:42:42
143883   2019-05-31 19:42:55
143884   2019-05-31 19:43:31
143885   2019-05-31 19:43:35
143886   2019-05-31 19:43:41
143887   2019-05-31 19:44:57
143888   2019-05-31 19:45:20
143889   2019-05-31 19:45:55
143890   2019-05-31 19:46:06
143891   2019-05-31 19:46:12
143892   2019-05-31 19:46:50
143893   2019-05-31 19:46:57
143894   2019-05-31 19:47:02
143895   2019-05-31 19:47:19
143896   2019-05-31 19:47:37
143897   2019-05-31 19:48:00
143898   2019-05-31 19:48:55
143899   2019-05-31 19:49:15
Name: Date/time, Length: 143900, dtype: datetime64[ns]

In [87]:
maxi=0
time='2019-05-30 01:11:51'
inside=[]

for index, row in rfid.iterrows():
    
    if row['Area'] != 'Esemény területén kívül':
        
        if row['RFID_id'] in inside:
            
            if len(inside) > maxi:
                
                maxi = len(inside)
                time = row['Date/time']
                
        else:

            inside.append(row['RFID_id'])
    else:
        
        if row['RFID_id'] in inside:
            
            inside.remove(row['RFID_id'])
        
print(maxi,time)

1870 2019-05-31 15:39:15

In [89]:
format_list = pd.DataFrame(columns=['MYTHBURN','ONE ON ONE','TURNING POINT','BATTLE OF MINDS','CHOSEN ONE','MINDBLOWN','ROUNDTABLE'])
format_list

Empty DataFrame
Columns: [MYTHBURN, ONE ON ONE, TURNING POINT, BATTLE OF MINDS, CHOSEN ONE, MINDBLOWN, ROUNDTABLE]
Index: []

In [90]:
for index, row in rfid.iterrows():
    
    for i, row1 in agenda.iterrows():
        
        if row['Date/time']>=row1['Date Start'] and row['Date/time']<=row1['Date End'] and 
        (row['Area']=='Big Hall' or row['Area']=='Secret Garden'):
            
            format_list=format_list.append({row1['Format']:row['RFID_id']}, ignore_index=True)

In [91]:
!telegram-send "Готово!"

In [94]:

format_list.nunique().sort_values(ascending=False)

TURNING POINT      2552
BATTLE OF MINDS    1471
MYTHBURN           1307
CHOSEN ONE         1089
MINDBLOWN          1026
ROUNDTABLE          868
ONE ON ONE          787
dtype: int64